theme: jekyll-theme-merlot
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
title: Belly Button Biodiversity Dashboard
description: Use this site to explore the various types of microbial species (also called operational taxonomic units, or OTUs, in the study) that were present in more than 70% of people. 
